"""Initial migration

Revision ID: e8b9b0a8a7a0
Revises: 
Create Date: 2025-10-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b9b0a8a7a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cover_letter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_template', sa.Text(), nullable=False, comment='Template content with placeholders like {position}, {company}, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_templates_id'), 'cover_letter_templates', ['id'], unique=False)
    op.create_index(op.f('ix_cover_letter_templates_name'), 'cover_letter_templates', ['name'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who owns this cover letter'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_id'), 'cover_letters', ['id'], unique=False)
    op.create_index(op.f('ix_cover_letters_is_default'), 'cover_letters', ['is_default'], unique=False)
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='Parent resume - cascade delete versions'),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_created_at'), 'resume_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_id'), 'resume_versions', ['id'], unique=False)
    op.create_index(op.f('ix_resume_versions_is_original'), 'resume_versions', ['is_original'], unique=False)
    op.create_index(op.f('ix_resume_versions_version'), 'resume_versions', ['version'], unique=False)
    op.create_table('cover_letter_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_letter_id', sa.Integer(), nullable=False, comment='Parent cover letter - cascade delete versions'),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_versions_created_at'), 'cover_letter_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_id'), 'cover_letter_versions', ['id'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_is_original'), 'cover_letter_versions', ['is_original'], unique=False)
    op.create_index(op.f('ix_cover_letter_versions_version'), 'cover_letter_versions', ['version'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='Original resume - protected from deletion'),
    sa.Column('resume_version_id', sa.Integer(), nullable=False, comment='Original resume version - protected from deletion'),
    sa.Column('customized_resume_version_id', sa.Integer(), nullable=True, comment='Customized version - deleted with application'),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True, comment='Cover letter master record - preserved on deletion (SET NULL)'),
    sa.Column('cover_letter_version_id', sa.Integer(), nullable=True, comment='Specific version of cover letter used for this application - protected from deletion'),
    sa.Column('customized_cover_letter_version_id', sa.Integer(), nullable=True, comment='Customized cover letter version for this application - deleted with application'),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_letter_version_id'], ['cover_letter_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customized_cover_letter_version_id'], ['cover_letter_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customized_resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_applied_date'), 'applications', ['applied_date'], unique=False)
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_cover_letter_id'), 'applications', ['cover_letter_id'], unique=False)
    op.create_index(op.f('ix_applications_cover_letter_version_id'), 'applications', ['cover_letter_version_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    
    op.execute("""
    INSERT INTO cover_letter_templates (name, description, content_template)
    VALUES 
    (
        'Professional Standard',
        'A formal, professional cover letter template suitable for most corporate positions',
        'Dear Hiring Manager,\n\nI am writing to express my strong interest in the {position} position at {company}. With my background in {field}, I am confident that I would be a valuable addition to your team.\n\n{highlight_experience}\n\nI am particularly drawn to {company} because {company_interest}. I believe my skills in {key_skills} align well with the requirements outlined in the job description.\n\n{additional_qualifications}\n\nI would welcome the opportunity to discuss how my experience and skills can contribute to {company}''s continued success. Thank you for considering my application.\n\nSincerely,\n{applicant_name}'
    ),
    (
        'Career Change',
        'Template for professionals transitioning to a new industry or role',
        'Dear Hiring Manager,\n\nI am excited to apply for the {position} role at {company}. While my background is in {previous_field}, I have developed transferable skills that make me an excellent candidate for this position.\n\n{transferable_skills}\n\nMy decision to transition into {new_field} stems from {motivation}. I have been actively preparing for this change by {preparation_activities}.\n\n{relevant_achievements}\n\nI am enthusiastic about bringing my unique perspective and diverse skill set to {company}. I am confident that my ability to {key_strength} will allow me to make meaningful contributions to your team.\n\nThank you for considering my application. I look forward to the opportunity to discuss how my background can benefit {company}.\n\nBest regards,\n{applicant_name}'
    ),
    (
        'Entry Level',
        'Template for recent graduates or professionals with limited experience',
        'Dear Hiring Manager,\n\nI am writing to apply for the {position} position at {company}. As a recent {degree} graduate from {university}, I am eager to begin my career in {industry} with your organization.\n\n{academic_achievements}\n\nDuring my studies, I developed strong skills in {key_skills} through {relevant_projects}. Additionally, my {internship_experience} provided me with practical experience in {relevant_areas}.\n\n{enthusiasm_and_motivation}\n\nI am impressed by {company}''s {company_achievement} and would be honored to contribute to your team. My fresh perspective, combined with my willingness to learn and grow, makes me an ideal candidate for this role.\n\nThank you for considering my application. I am excited about the possibility of starting my career at {company}.\n\nSincerely,\n{applicant_name}'
    ),
    (
        'Technical Role',
        'Template optimized for software engineering and technical positions',
        'Dear Hiring Manager,\n\nI am writing to apply for the {position} role at {company}. With {years_experience} years of experience in {technical_domain}, I am excited about the opportunity to contribute to your engineering team.\n\n{technical_expertise}\n\nMy experience includes working with {technologies} and successfully delivering {project_types}. At {previous_company}, I {technical_achievement}, which resulted in {measurable_impact}.\n\n{problem_solving_example}\n\nI am particularly interested in {company}''s work on {company_projects}. I believe my expertise in {specialization} would enable me to make immediate contributions to your team while continuing to grow as an engineer.\n\n{additional_technical_skills}\n\nI would welcome the opportunity to discuss how my technical skills and experience align with your needs. Thank you for your consideration.\n\nBest regards,\n{applicant_name}'
    ),
    (
        'Executive/Leadership',
        'Template for senior-level and executive positions',
        'Dear {recipient_title} {recipient_name},\n\nI am writing to express my interest in the {position} role at {company}. With over {years_experience} years of progressive leadership experience in {industry}, I am confident in my ability to drive strategic initiatives and deliver exceptional results for your organization.\n\n{leadership_achievements}\n\nThroughout my career, I have demonstrated success in {key_leadership_areas}. At {current_company}, I led {major_initiative}, resulting in {quantifiable_results}. My leadership philosophy centers on {leadership_approach}, which has consistently enabled teams to exceed performance targets.\n\n{strategic_vision}\n\nI am impressed by {company}''s position in {market_position} and your commitment to {company_values}. I believe my experience in {relevant_experience} positions me to make significant contributions to your continued growth and success.\n\n{executive_capabilities}\n\nI would appreciate the opportunity to discuss how my strategic vision and proven track record align with {company}''s objectives. Thank you for your consideration.\n\nSincerely,\n{applicant_name}\n{applicant_title}'
    )
    ON CONFLICT DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM cover_letter_templates")
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_cover_letter_version_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_cover_letter_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_date'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_cover_letter_versions_version'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_is_original'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_id'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_created_at'), table_name='cover_letter_versions')
    op.drop_table('cover_letter_versions')
    op.drop_index(op.f('ix_resume_versions_version'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_is_original'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_created_at'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_is_default'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_cover_letter_templates_name'), table_name='cover_letter_templates')
    op.drop_index(op.f('ix_cover_letter_templates_id'), table_name='cover_letter_templates')
    op.drop_table('cover_letter_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
